---
antora:
  name: modules
  dir: www
  modules:
    - name: "01-sudoers"
      label: "Sudoers"
      solveButton: true
    - name: "02-flag"
      label: "Flag"
      solveButton: true

tabs:
  - name: ">_ terminal"
    url: /wetty_rhel/ssh/root
    modules:
      - "01-sudoers"
