#!/usr/bin/env bash
#

echo "Stopping serve process..."

# Check if podman exists, otherwise use docker
CONTAINER_CMD="docker"
if command -v podman &> /dev/null; then
    CONTAINER_CMD="podman"
fi

$CONTAINER_CMD stop showroom-server

echo "Serve process stopped."
