#!/usr/bin/env bash
#

echo "Starting serve process..."

# Check if podman exists, otherwise use docker
CONTAINER_CMD="docker"
if command -v podman &> /dev/null; then
    CONTAINER_CMD="podman"
fi

$CONTAINER_CMD run -d --rm --name showroom-server -p 8443:8080 -v "./www:/usr/share/nginx/html:Z" docker.io/nginx:alpine

echo "Serve process complete."
echo "Browse to http://localhost:8443/index.html"
