---
virtualmachines:
  - name: "rhel"
    image: "rhel-10-0-beta"
    memory: "4G"
    cores: 1
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
